image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  PROJECTS: prestashop-nginx;prestashop-fpm;prestashop-autobackup

services:
- docker:dind

before_script:
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
- apk add --no-cache py-pip
- pip install docker-compose
- for PROJ in ${PROJECTS//;/ }; do docker pull $CI_REGISTRY_IMAGE/$PROJ:latest || true; done

build:
  script:
    - docker-compose build --pull
    - docker-compose push