version: '3.2'

services:
  nginx:
    image: ${CI_REGISTRY_IMAGE}/prestashop-nginx:latest
    build: 
      context: docker-images/prestashop-nginx
      cache_from:
        - ${CI_REGISTRY_IMAGE}/prestashop-nginx:latest
    restart: always
    volumes:
      - prestashop-data:/var/www/html/
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    depends_on:
      - prestashop

  prestashop:
    image: ${CI_REGISTRY_IMAGE}/prestashop-fpm:latest
    build: 
      context: docker-images/prestashop-fpm
      cache_from:
        - ${CI_REGISTRY_IMAGE}/prestashop-fpm:latest
    restart: always
    volumes:
      - prestashop-data:/var/www/html/
    networks:
      - frontend
      - db
      - cache
    depends_on:
      - db
      - memcached
    environment:
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
    deploy:
      placement:
        constraints: [node.labels.my-service == true]

  db:
    image: percona
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=example
    deploy:
      placement:
        constraints: [node.labels.my-service == true]

  adminer:
    image: adminer
    ports:
      - 9010:8080
    networks:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  memcached:
    image: memcached:alpine
    networks:
      - cache
    deploy:
      restart_policy:
        max_attempts: 3
        window: 60s
 
volumes:
  db-data:
  prestashop-data:

networks:
  frontend:
  db:
  cache: