version: '3.2'

services:
  nginx:
    image: ${CI_REGISTRY_IMAGE}/prestashop-nginx:latest
    build: 
      context: docker-images/prestashop-nginx
      cache_from:
        - ${CI_REGISTRY_IMAGE}/prestashop-nginx:latest
    restart: always
    volumes:
      - prestashop-data:/var/www/html/
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    depends_on:
      - prestashop

  prestashop:
    image: ${CI_REGISTRY_IMAGE}/prestashop-fpm:latest
    build: 
      context: docker-images/prestashop-fpm
      cache_from:
        - ${CI_REGISTRY_IMAGE}/prestashop-fpm:latest
    restart: always
    volumes:
      - prestashop-data:/var/www/html/
    networks:
      - frontend
      - db
      - cache
    depends_on:
      - db
      - memcached
    environment:
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
    deploy:
      placement:
        constraints: [node.labels.my-service == true]

  db:
    image: percona
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
    secrets:
      - mysql-root-password
    deploy:
      placement:
        constraints: [node.labels.my-service == true]

  adminer:
    image: adminer
    ports:
      - 9010:8080
    networks:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  autobackup:
    image: ${CI_REGISTRY_IMAGE}/prestashop-autobackup:latest
    build: 
      context: docker-images/prestashop-autobackup
      cache_from:
        - ${CI_REGISTRY_IMAGE}/prestashop-autobackup:latest
    volumes:
      - db-data:/var/lib/mysql
      - prestashop-data:/data/prestashop
    networks:
      - db
    environment:
      - DUPLICACY_BACKUP_OPTIONS=-threads 1 -stats
      - BACKUP_NAME=${BACKUP_NAME}
      - BACKUP_LOCATION=${BACKUP_LOCATION}
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE}
      - B2_ID_FILE=/run/secrets/b2_id
      - B2_KEY_FILE=/run/secrets/b2_key
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-root-password
    secrets:
      - b2_id
      - b2_key
      - mysql-root-password
    deploy:
      restart_policy:
        max_attempts: 3
        window: 60s
      placement:
        constraints: [node.labels.my-service == true]

  memcached:
    image: memcached:alpine
    networks:
      - cache
    deploy:
      restart_policy:
        max_attempts: 3
        window: 60s
 
volumes:
  db-data:
  prestashop-data:

networks:
  frontend:
  db:
  cache:

secrets:
  mysql-root-password:
    external: true
  b2_id:
    external: true
  b2_key:
    external: true
